# Generated by Django 4.2 on 2023-04-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='bio',
            field=models.TextField(blank=True, default='Hello!'),
        ),
    ]
