# Generated by Django 4.2 on 2023-09-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
