# Generated by Django 4.2 on 2023-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profiledetail_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='bio',
            field=models.TextField(default='Hello!'),
        ),
    ]
