# Generated by Django 4.2 on 2023-04-12 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 10, 36, 35, 708213, tzinfo=datetime.timezone.utc)),
        ),
    ]
