# Generated by Django 4.2 on 2023-05-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmodel_c_user_alter_chatmodel_chat_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
