# Generated by Django 4.2 on 2023-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
