# Generated by Django 4.2 on 2023-05-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_receiver_message_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_name',
            field=models.CharField(max_length=100),
        ),
    ]
